### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by havenindustries** [auth0-samples/auth0-aspnetcore-webapi-samples#11]
There appears to be no way to make this work.  The calls always result in unauthorized 401 errors.

**Comment by jerriep** [comment]
@havenindustries Please have a look at the troubleshooting section of our ASP.NET Core Web API quickstart:
https://auth0.com/docs/quickstart/backend/aspnet-core-webapi/03-troubleshooting

If your problem still persist, please contact Auth0 support, as they can better assist you:
https://support.auth0.com/
