### ISSUE TITLE
WebApp ASP.net Core: Security Warning received from firefox browser.

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-aspnetcore-webapi-samples#17]
After click in the "LOG IN" button, using firefox browser, a security warning is received.

![image](https://user-images.githubusercontent.com/26749061/33333549-83b95bc6-d43d-11e7-8d94-f4d963964346.png)

Firefox version:

![image](https://user-images.githubusercontent.com/26749061/33333666-d11d6b78-d43d-11e7-8a02-2202569d44b8.png)

**Comment by jerriep** [comment]
@HeikerAraujo Can you please be a bit more clear as to what sample app it is you were running? Or how you got this log in screen?

This repository is for the Web API samples. None of the samples here contain log in screens. So in order for me to help you successfully you need to give me **much** more context please
