### ISSUE TITLE
No Error message in response

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-aspnetcore-webapi-samples#19]
There's no error message displayed while calling the API without a proper access_token

![image](https://user-images.githubusercontent.com/15782359/34388824-63d64734-eb0c-11e7-8460-711c58974ea7.png)

![image](https://user-images.githubusercontent.com/15782359/34388829-6b3a8da0-eb0c-11e7-86f7-3fea7c6d6784.png)

It should be displayed an error message specifing the error code.

**Comment by jerriep** [comment]
@rafanog There is not much I can do about this, as this is how the built-in ASP.NET Core middleware works. If you need a custom error message then either (1) open an issue on the ASP.NET Core repo (https://github.com/aspnet/security) and request this or (2) write your own JWT middleware which does this

Sorry for the non-response, but we rely on the standard ASP.NET Core infrastructure and have no intention of writing and maintaining our own middleware for this.
