### ISSUE TITLE
GetUserInfoAsync() - All properties are null beside 'sub'

### ISSUE THREAD

**Issue by dannyyy** [auth0-samples/auth0-aspnetcore-webapi-samples#20]
I have used your sample code to retrieve the user information. But the response only includes the 'sub' claim. All the other properties are null.

Also a manuel request with Postman has the same outcome.

I only get a real result if I request the userinfo-endpoint with the POST method and add the access_token to the post data. Is the API outdated or do I something wrong?

**Comment by jerriep** [comment]
@dannyyy This repository contains quite a few samples, so I am not sure exactly what you are refering to. I assume it is the Samples/user-info sample, but even that one contains various ways in which to achieve this.

Please attached a complete sample which reproduces the problem to this issue so I can look into it

**Comment by jerriep** [comment]
@dannyyy I am closing this issue as I cannot assist with the information provided. If you can provide a sample demonstrating the issue, please feel free to re-open
