### ISSUE TITLE
User.Claims is empty in HandleRequirementAsync

### ISSUE THREAD

**Issue by iSatishYadav** [auth0-samples/auth0-aspnetcore-webapi-samples#25]
## User.Claims is empty in HandleRequirementAsync.

https://github.com/auth0-samples/auth0-aspnetcore-webapi-samples/blob/52daac6459a7716cdb880f27e0d035cb186a18a5/Quickstart/01-Authorization/HasScopeHandler.cs#L12

**Comment by damieng** [comment]
Are you still having this problem?
