### ISSUE TITLE
.NET 6 Support

### ISSUE THREAD

**Issue by ICanDoThings2** [auth0-samples/auth0-aspnetcore-webapi-samples#39]
Will support come for this for .NET 6? I was using the tutorial here; https://auth0.com/docs/quickstart/backend/aspnet-core-webapi/01-authorization but it doesn't seem for the recent version, which has no more startup.cs , and it looks like a lot of the project was updated last years ago.

**Comment by frederikprijck** [comment]
Hey,

.NET 6 on its own can still use a startup file. I assume you are talking about the minimal API that comes with .NET 6?
Even then you could have a Startup file if you'd like: https://www.c-sharpcorner.com/article/how-to-add-startup-cs-class-in-asp-net-core-6-project/

That said, that startup file is just some syntactic sugar, so you should be able to use it in a comparable without a Startup file:

```
var builder = WebApplication.CreateBuilder(args);

// ...

string domain = $"https://{Configuration["Auth0:Domain"]}/";
builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.Authority = domain;
        options.Audience = Configuration["Auth0:Audience"];
        options.TokenValidationParameters = new TokenValidationParameters
        {
            NameClaimType = ClaimTypes.NameIdentifier
        };
    });

var app = builder.Build();

// ...
app.UseAuthentication();
app.UseAuthorization();
app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "default",
            template: "{controller=Home}/{action=Index}/{id?}");
    });
app.Run();
```

Would that help?

**Comment by ICanDoThings2** [comment]
Yeah. I see what you're getting. The Program.cs file exists still, and I figure I could plop it in that. It was giving me some weirdness with setting the domain though and reading it from the JSON file.
