### ISSUE TITLE
ValidateIssuerSigningKey for RSA JWT 

### ISSUE THREAD

**Issue by AhmedFay** [auth0-samples/auth0-aspnetcore-webapi-samples#40]
in the 01-Authorization example or in the official website there is nothing about the validation issuer signing key, 
but in old versions ".net framework", there was an example in validation it, 

in this example, is this just fine to validate the token?
  ```C#
  var domain = $"https://{Configuration["Auth0:Domain"]}/";
  services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(options =>
{
	options.Authority = domain;
	options.Audience = Configuration["Auth0:Audience"];
});
```

or I need to write IssuerSigningKeyResolver to get jwks from the ".well-known/jwks.json" path, like this? 

  ```C#
  var domain = $"https://{Configuration["Auth0:Domain"]}/";
  services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(options =>
{
	options.Authority = domain;
	options.Audience = Configuration["Auth0:Audience"];
	options.TokenValidationParameters = new TokenValidationParameters
       {
           ValidateIssuerSigningKey = true,
           IssuerSigningKeyResolver = (token, securityToken, kid, parameters) =>
           {
               var client = new HttpClient();
               var jwksUri = new Uri($"{domain}.well-known/jwks.json");
               var jwksJson = client.GetStringAsync(jwksUri).GetAwaiter().GetResult();

               var jwks = JsonConvert.DeserializeObject<JsonWebKeySet>(jwksJson);
               return jwks.Keys;
           }
       };

});
```

**Comment by frederikprijck** [comment]
Thanks for reaching out. The first example should be enough, the middleware should call the jwks endpoint for you, calculating the URL based on the Authority you configure.

**Comment by AhmedFay** [comment]
> Thanks for reaching out. The first example should be enough, the middleware should call the jwks endpoint for you, calculating the URL based on the Authority you configure, and validate the issuer accordingly.
> 
> I do recommend you to reach out to the docs for that library if you need more complicated configuration that is outside of the scope of this sample.

Thank you for your response. I appreciate your suggestion, will check the docs, 
I just wanted to be sure everything is secure due to the differences between the samples.
