### ISSUE TITLE
This does not work

### ISSUE THREAD

**Issue by DasNaughtie** [auth0-samples/auth0-aspnetcore-webapi-samples#43]
I've followed this and the handler never finds the claims because their always empty.  Either the documentation is incomplete or this is out of date because it doesn't work and there no decent documentation on how to do this.  None of the guides on the website work either.

**Comment by frederikprijck** [comment]
Thanks for reaching out.

When I run the sample application, and call the `private-scoped` endpoint with a token, set as the Authorization header, that has the `read:messages` scope, I am able to get to the controller successfully and the scopes are found in the `HasScopeHandler`:

![image](https://user-images.githubusercontent.com/2146903/224949405-b9e291dd-edf8-4ebc-b536-e01bd282f3fb.png)

Have you verified your token contains the required scopes? You can use www.jwt.io to decode your token and look at its scope property, you should see something like this:

![image](https://user-images.githubusercontent.com/2146903/224949794-d7d07b53-b260-4e6d-bdc5-010d57f01ccf.png)

**Comment by DasNaughtie** [comment]
Hi Frederickprijck,

Thanks for getting back to me.

I've opted to use the RBAC option so have checked that an can confirm the permissions are visible in the token.  However, when I attempt to debug I don't see any claims at all:

![image](https://user-images.githubusercontent.com/6909205/224951399-9e51e401-115f-4530-aa80-2a4fb1b275de.png)

so at a bit of a loss.

**Comment by DasNaughtie** [comment]
In this case I've used postman to get a token and then tried to hit a protected endpoint on my local.

**Comment by DasNaughtie** [comment]
I know...I'm at a bit of a loss myself.

I've checked the details of the token on jwt.io and everything seems to be in order.  And definitely adding it as a Authorization header in Postman but still coming through empty when it hits the endpoint.

**Comment by DasNaughtie** [comment]
Any ideas?

**Comment by frederikprijck** [comment]
I'm sorry, but there isn't much we can help with based on the information provided.

If the user is marked as not authenticated, and there is no claim set, I believe we shouldn't focus on the permissions claims or the Handler, but try and figure out why the token isn't being accepted.

Things I can think of (but have already mentioned) are:
- Ensure audience in the API project is the same as in the token
- Ensure the domain is correct in the API project
- Ensure you sent a non expired token

Can you reproduce the behavior you are experiencing with our Sample app?

**Comment by DasNaughtie** [comment]
Just found out from one of the UI team that they've added a Rule to Auth0 pipeline:

![image](https://user-images.githubusercontent.com/6909205/224992029-6ee26d63-a88f-41e2-bf6c-fe34f261e3b0.png)

Can't see why this would affect my local but thought I'd ask all the same.
I'll try to give it a test with you sample and let you know how I get along.

**Comment by DasNaughtie** [comment]
Hi there....
Downloaded your sample and it worked first time so the issue is definitely with my implementation.  Going to see if I can get to the bottom of the issue...if I do then will post here at least for future reference should anyone else ask about or come across this in future.

**Comment by frederikprijck** [comment]
Thanks, let me know if I can still help.

Closing this for now, but happy to reopen as needed.
